# Generated by Django 3.2 on 2022-04-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
